# docker/Dockerfile.frontend
FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

# Clean default nginx content
RUN rm -rf ./*

# Copy HTML files from repo root
COPY ./index.html ./
COPY ./*.html ./

# Copy static assets
COPY ./CSS ./CSS
COPY ./Images ./Images
COPY ./Javascript ./Javascript

# Custom nginx config
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
