apiVersion: v1
kind: Pod
metadata:
  name: db-app
  labels:
    app: db
spec:
  containers:
    - name: postgres-app
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
          name: postgress